services:

  gharseva-backend:

    build: .

    container_name: gharseva-backend

    restart: unless-stopped

    env_file:
      - .env

    labels:

      - "traefik.enable=true"
      - "traefik.http.routers.gharseva.rule=Host(`api.gharseva.imohit1o1.online`)"
      - "traefik.http.routers.gharseva.entrypoints=websecure"
      - "traefik.http.routers.gharseva.tls.certresolver=myresolver"
      - "traefik.http.services.gharseva.loadbalancer.server.port=8000"

    networks:
      - edge

networks:

  edge:
    external: true